/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { AuthenticityNFT } from "./AuthenticityNFT";
export type { AuthenticityRegistry } from "./AuthenticityRegistry";
export type { SimpleAuthenticityNFT } from "./SimpleAuthenticityNFT";
export type { TestContract } from "./TestContract";
