/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { AuthenticityNFT__factory } from "./AuthenticityNFT__factory";
export { AuthenticityRegistry__factory } from "./AuthenticityRegistry__factory";
export { SimpleAuthenticityNFT__factory } from "./SimpleAuthenticityNFT__factory";
export { TestContract__factory } from "./TestContract__factory";
